"""Add sport_units to User

Revision ID: f5b2614e18cf
Revises: 5fe85178421f
Create Date: 2023-09-29 22:53:06.541553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b2614e18cf'
down_revision = '5fe85178421f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport_units', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sport_units')

    # ### end Alembic commands ###
